name: careergraph-api
version: '3.8'

services:
  # --- DATABASE: Postgres với PGVector ---
  careergraph-db:
    image: pgvector/pgvector:pg16
    container_name: careergraph-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=careergraph
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - careergraph-network
    volumes:
      - pg_dt:/var/lib/postgresql/data

  # --- CACHE: Redis ---
  careergraph-redis:
    image: redis:latest
    container_name: careergraph-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - careergraph-network
    volumes:
      - redis_dt:/data

#  # --- APP: Spring Boot API ---
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: careergraph-api
#    ports:
#      - "8080:8080"
#    restart: unless-stopped
#    depends_on:
#      careergraph-db:
#        condition: service_started
#      careergraph-redis:
#        condition: service_started
#      careergraph-elasticsearch:
#        condition: service_healthy
#    networks:
#      - careergraph-network

  # --- SEARCH: Elasticsearch ---
  careergraph-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.5
    container_name: careergraph-elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=demo-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - careergraph-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep '\"status\":\"green\\|yellow\"'" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - es_dt:/usr/share/elasticsearch/data

networks:
  careergraph-network:
    driver: bridge

volumes:
  es_dt:
  pg_dt:
  redis_dt: # Lưu trữ dữ liệu Redis