package com.hcmute.careergraph.enums.notification;

public enum NotificationType {
  NEW_MESSAGE,
  APPLICATION_STATUS_CHANGED,
  NEW_APPLICATION,
  APPLICATION_VIEWED,
  APPLICATION_SHORTLISTED,
  APPLICATION_REJECTED,
  APPLICATION_INTERVIEW_SCHEDULED,
  INTERVIEW_CONFIRMED,
  INTERVIEW_DECLINED,
  INTERVIEW_CANCELLED,
  INTERVIEW_RESCHEDULE_PROPOSED,
  INTERVIEW_RESCHEDULE_ACCEPTED,
  INTERVIEW_RESCHEDULE_REJECTED,
  /** HR: AI đã chấm điểm / sàng lọc hồ sơ sau khi ứng viên apply */
  APPLICATION_AI_SCREENING
}
