package com.hcmute.careergraph.enums.notification;

public enum NotificationType {
  NEW_MESSAGE,
  APPLICATION_STATUS_CHANGED,
  NEW_APPLICATION,
  APPLICATION_VIEWED,
  APPLICATION_SHORTLISTED,
  APPLICATION_REJECTED,
  APPLICATION_INTERVIEW_SCHEDULED
}
